ASP.NET/MovieFlix/MovieFlix/Controllers/CastController.cs
using Microsoft.AspNetCore.Mvc;
using MovieFlix.Core.Contracts.Service;
using MovieFlix.Core.Models;

namespace MovieFlix.Controllers
{
    public class CastController : Controller
    {
        private readonly ICastServiceAsync castServ;
        private readonly IMovieCastServiceAsync movieCastServ;

        public CastController (ICastServiceAsync castServ, IMovieCastServiceAsync movieCastServ)
        {
            this.castServ = castServ;
            this.movieCastServ = movieCastServ;
        }
        [HttpGet]
        public async Task<IActionResult> ShowAllMoviesByCast(int castId)
        {
            IEnumerable<MoviesByCastModel> moviesByCast = await movieCastServ.GetAllMoviesByCastId(castId);
            return View(moviesByCast);
        }

    }
}

ASP.NET/MovieFlix/MovieFlix/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieFlix.Core.Contracts.Service;
using MovieFlix.Core.Entities;
using MovieFlix.Core.Models;
using MovieFlix.Models;
using System.Diagnostics;
using User = MovieFlix.Core.Entities.User;

namespace MovieFlix.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieServiceAsync movieServ;
        private readonly IMovieCastServiceAsync movieCastServ;
        private readonly ICastServiceAsync castServ;
        private int savedMovieId;
        private readonly SignInManager<User> signInManager;


        public MoviesController(IMovieServiceAsync movieServ, IMovieCastServiceAsync movieCastServ, ICastServiceAsync castServ, SignInManager<User> signInManager)
        {
            this.movieServ = movieServ;
            this.movieCastServ = movieCastServ;
            this.castServ = castServ;
            this.signInManager = signInManager;
        }

        public async Task<IActionResult> Index()
        {
            var allMovies = await movieServ.GetAllMoviesAsync();
            return View(allMovies);
        }

        public IActionResult Privacy()
        {
            return View();
        }
        [HttpGet]
        ///[Authorize]
        public IActionResult CreateMovie()
        {
            return View();
        }
        [HttpPost]
        //[Authorize]
        public async Task<IActionResult> CreateMovie(MovieModel model)
        {
            if (ModelState.IsValid)
            {
                await movieServ.InsertMovieAsync(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int movieId)
        {
            MovieModel movieModel = await movieServ.GetMovieByIdAsync(movieId);
            movieModel.MovieCasts = await movieCastServ.GetAllMovieCastByMovieId(movieId);

            return View(movieModel);
        }


        [HttpGet]
        //[Authorize]
        public IActionResult CreateCast(int movieId)
        {
            return View(movieId);
        }
        [HttpPost]
        //[Authorize]
        public async Task<IActionResult> CreateCast(CastModel model)
        {
            if (ModelState.IsValid)
            {
                await castServ.InsertCastAsync(model);
                return RedirectToAction("Index");
                
            }
            return View(model);
        }

        [HttpGet]
        //[Authorize]
        public async Task<IActionResult> ChooseCast(int movieId)
        {
            this.savedMovieId = movieId;
            var allCast = await castServ.GetAllCastsAsync();
            ViewBag.MovieId = movieId;
            return View(allCast);
        }

        [HttpGet]
        //[Authorize]
        public async Task<IActionResult> CreateMovieCast(int castId, int movieId)
        {
            var model = await castServ.GetCastByIdAsync(castId);
            ViewBag.MovieId = movieId;
            return View(model);
        }
        [HttpPost]
        //[Authorize]
        public async Task<IActionResult> CreateMovieCast(MovieCastModel model)
        {
            if (ModelState.IsValid)
            {
                await movieCastServ.InsertMovieCastAsync(model);
                return RedirectToAction("Index");
            }
            
            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET/MovieFlix/MovieFlix/Views/Movies/ChooseCast.cshtml
<div class="row">
	@{
    
    foreach (var castModel in Model)
    {
            <div class="col-3">
                <partial name="_CastCard" model="castModel"/>
            </div>
    }
}
</div>

ASP.NET/MovieFlix/MovieFlix/Views/Movies/CreateCast.cshtml
<form asp-action="CreateCast" asp-controller="Movies" as method="post">
    
        <div class="form-group mb-3 text-light">
            <label for="Name">Name</label>
            <input type="text" class="form-control" id="name" name="Name" placeholder="Enter Name">
        </div>
        <div class="form-group mb-3 text-light">
            <label for="Gender">Gender</label>
            <input type="text" class="form-control" id="Gender" name="Gender" placeholder="Enter Gender">
        </div>
        <div class="form-group mb-3 text-light">
            <label for="TmdbUrl">TmdbUrl</label>
            <input type="url" class="form-control" id="TmdbUrl" name="TmdbUrl" placeholder="Enter TmdbUrl">
        </div>
    
        <div class="form-group mb-3 text-light">
            <label for="ProfilePath">ProfilePath</label>
            <input type="url" class="form-control" id="ProfilePath" name="ProfilePath" placeholder="Enter ProfilePath">
        </div>

  <input type="submit" class="btn btn-primary mt-3" value="Save"/>
</form>

ASP.NET/MovieFlix/MovieFlix/Views/Movies/CreateMovie.cshtml
<form asp-action="CreateMovie" asp-controller="Movies" method="post">
    <div class="row">
        <div class="form-group col-4 mb-3 text-light">
            <label for="Title">Title</label>
            <input type="text" class="form-control" id="Title" name="Title" placeholder="Enter Title">
        </div>
        <div class="form-group col-4 mb-3 text-light">
            <label for="Overview">Overview</label>
            <input type="text" class="form-control" id="Overview" name="Overview" placeholder="Enter Overview">
        </div>
        <div class="form-group col-4 mb-3 text-light">
            <label for="Tagline">Tagline</label>
            <input type="text" class="form-control" id="Tagline" name="Tagline" placeholder="Enter Tagline">
        </div>
    </div>
    <div class="row">
        <div class="form-group col-4 mb-3 text-light">
            <label for="Budget">Budget</label>
            <input type="number" step="0.01" class="form-control" id="Budget" name="Budget" placeholder="Enter Budget">
        </div>
        <div class="form-group col-4 mb-3 text-light">
            <label for="Revenue">Revenue</label>
            <input type="number" step="0.01" class="form-control" id="Revenue" name="Revenue" placeholder="Enter Revenue">
        </div>
        <div class="form-group col-4 mb-3 text-light">
            <label for="ImdbUrl">ImdbUrl</label>
            <input type="url" class="form-control" id="ImdbUrl" name="ImdbUrl" placeholder="Enter ImdbUrl">
        </div>
    </div>
    <div class="row">
        <div class="form-group col-4 mb-3 text-light">
            <label for="TmdbUrl">TmdbUrl</label>
            <input type="url" class="form-control" id="TmdbUrl" name="TmdbUrl" placeholder="Enter TmdbUrl">
        </div>
        <div class="form-group col-4 mb-3 text-light">
            <label for="PosterUrl">PosterUrl</label>
            <input type="url" class="form-control" id="PosterUrl" name="PosterUrl" placeholder="Enter PosterUrl">
        </div>
        <div class="form-group col-4 mb-3 text-light">
            <label for="BackdropUrl">BackdropUrl</label>
            <input type="url" class="form-control" id="BackdropUrl" name="BackdropUrl" placeholder="Enter BackdropUrl">
        </div>
    </div>
    <div class="row">
        <div class="form-group col-4 mb-3 text-light">
            <label for="OriginalLanguage">OriginalLanguage</label>
            <input type="text" class="form-control" id="OriginalLanguage" name="OriginalLanguage" placeholder="Enter OriginalLanguage">
        </div>
        <div class="form-group col-4 mb-3 text-light">
            <label for="ReleaseDate">ReleaseDate</label>
            <input type="datetime" class="form-control" id="ReleaseDate" name="ReleaseDate" placeholder="Enter ReleaseDate">
        </div>
        <div class="form-group col-4 mb-3 text-light">
            <label for="Runtime">Runtime</label>
            <input type="number" step="0.01" class="form-control" id="Runtime" name="Runtime" placeholder="Enter Runtime">
        </div>
    </div>
    <div class="row">
        <div class="form-group col-4 mb-3 text-light">
            <label for="Price">Price</label>
            <input type="number" step="0.01" class="form-control" id="Price" name="Price" placeholder="Enter Price">
        </div>
        <div class="form-group col-4 mb-3 text-light">
            <label for="CreatedDate">CreatedDate</label>
            <input type="datetime" class="form-control" id="CreatedDate" name="CreatedDate" placeholder="Enter CreatedDate">
        </div>
        <div class="form-group col-4 mb-3 text-light">
            <label for="UpdatedDate">UpdatedDate</label>
            <input type="datetime" class="form-control" id="UpdatedDate" name="UpdatedDate" placeholder="Enter UpdatedDate">
        </div>
    </div>
    <div class="row">
        <div class="form-group col-6 mb-3 text-light">
            <label for="UpdatedBy">UpdatedBy</label>
            <input type="text" class="form-control" id="UpdatedBy" name="UpdatedBy" placeholder="Enter UpdatedBy">
        </div>
        <div class="form-group col-6 mb-3 text-light">
            <label for="CreatedBy">CreatedBy</label>
            <input type="text" class="form-control" id="CreatedBy" name="CreatedBy" placeholder="Enter CreatedBy">
        </div>
    </div>

  <input type="submit" class="btn btn-primary" value="Save"/>
</form>

ASP.NET/MovieFlix/MovieFlix/Views/Movies/CreateMovieCast.cshtml
<form asp-action="CreateMovieCast" asp-controller="Movies" as method="post">
        <div class="form-group mb-3 text-light">
            <label for="MovieId">MovieId</label>
            <input type="text" class="form-control" id="MovieId" name="MovieId" value=@ViewBag.MovieId readonly>
        </div>

        <div class="form-group mb-3 text-light">
            <label for="CastId">CastId</label>
            <input type="text" class="form-control" id="CastId" name="CastId" value=@Model.Id readonly>
        </div>
        <div class="form-group mb-3 text-light">
            <label for="Character">Character</label>
            <input type="text" class="form-control" id="Character" name="Character" placeholder="Enter Character Name">
        </div>

  <input type="submit" class="btn btn-primary mt-3" value="Save"/>
</form>

ASP.NET/MovieFlix/MovieFlix/Views/Movies/Detail.cshtml
<section>
<div class="container">
	<div class="row" >
		<div class="background-image" style="background-image: url(@Model.BackdropUrl);"></div>

			<div class="col-2" >
				<img class="img-fluid rounded" src=@Model.PosterUrl alt="Card image cap">
			</div>
			<div class="col-8">
				<ul class="text-white" style="list-style-type:none;">
					<li class="m-3"><h1>@Model.Title</h1></li>
					<li class="text-muted m-3">@Model.Tagline</li>
					<li class="text-muted m-3 fw-bold">@Model.RunTime m | @Model.ReleaseDate.ToShortDateString()</li>
					<li class="m-3">@Model.Overview</li>
				</ul>
			</div>
			<div class="col-2">
				<div><a class="btn btn-warning mb-3">Review</a></div>
				<div><a class="btn btn-warning mb-3">BUY $@Model.Price</a></div>
			</div>
	</div>
</div>
<div class="container mt-lg-5" style="margin-top:200px">
	<div class="row">
		<div class="col-6 bg-gradient rounded">
			<div class="text-white">MOVIE FACTS</div>
			<ul class="text-white my-3" style="list-style-type:none;">
				<li style="font-size:14px">>Release Date <span class="bg-gradient px-1 rounded">@Model.ReleaseDate.ToShortDateString()</span></li>
				
				<hr />
				<li style="font-size:14px">>Run Time <span class="bg-gradient px-1 rounded">@Model.RunTime</span></li>
				<hr />
				<li style="font-size:14px">>Box Office <span class="bg-gradient px-1 rounded">@Model.Revenue</span></li>
				<hr />
				<li style="font-size:14px">>Budget <span class="bg-gradient px-1 rounded">@Model.Budget</span></li>
			</ul>
			<div class="text-white mb-3">TRAILERS</div>
			<div class="text-white"></div>
		</div>
		<div class="col-6">
			@{
				foreach (var item in Model.MovieCasts)
				{
						<a
					class="text-decoration-none" asp-action="ShowAllMoviesByCast" asp-controller="Cast" asp-route-castId="@item.CastId" method="get">
						<div class="text-white mx-5">
						<img class="card-img rounded-circle mx-2" style="width:50px" src="@item.Cast.ProfilePath"/>
						<span class="mx-2" style="font-size:14px">@item.Cast.Name</span>
						<span class="mx-2" style="font-size:14px">@item.Character</span>
						</div>
						</a>
				}
			}
		</div>
	</div>
</div>
</section>


<div class="fixed-bottom" style="
    bottom: 80px;
    left: 80%;
    margin-left: -104.5px;">
    <a class="btn btn-warning " asp-action="ChooseCast" asp-controller="Movies" asp-route-movieId="@Model.Id">Add Cast For This Movie</a></div>

ASP.NET/MovieFlix/MovieFlix/Views/Movies/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    @{foreach(MovieModel movieModel in Model)
        {
            <div class="col-3">
                <partial name="_MovieCard" model="movieModel"/>
            </div>
        }
    }
</div>

<div class="fixed-bottom" style="
    bottom: 130px;
    left: 80%;
    margin-left: -104.5px;">
    <a class="btn btn-warning " asp-action="CreateCast" asp-controller="Movies">Add Cast</a></div>
<div class="fixed-bottom" style="
    bottom: 80px;
    left: 80%;
    margin-left: -104.5px;">
    <a class="btn btn-warning " asp-action="CreateMovie" asp-controller="Movies">Add Movie</a></div>